# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector
import datetime

con = mysql.connector.connect(
    host="localhost", user="root", password="MySql@2157", database="attendance")
if con.is_connected():
    print("conect ayyindhi bhaiyya")

my_cursor = con.cursor()
my_cursor.execute("use attendance")
# my_cursor.execute('CREATE TABLE nominal_mor (roll_no VARCHAR(20) PRIMARY KEY,user_name VARCHAR(121),today DATETIME)')
# my_cursor.execute('CREATE TABLE nominal_eve (roll_no VARCHAR(20) PRIMARY KEY,user_name VARCHAR(121),today DATETIME)')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(565, 395)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 30, 101, 41))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 91, 21))
        self.label_2.setObjectName("label_2")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 90, 113, 22))
        self.lineEdit.setObjectName("lineEdit")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 160, 81, 16))
        self.label_3.setObjectName("label_3")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 160, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(270, 220, 91, 31))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 225, 71, 21))
        self.label_4.setObjectName("label_4")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(412, 287, 121, 31))
        self.pushButton.setObjectName("pushButton")

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 565, 26))
        self.menubar.setObjectName("menubar")

        self.menuAttendance = QtWidgets.QMenu(self.menubar)
        self.menuAttendance.setObjectName("menuAttendance")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAttendance.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.label.setText(_translate("MainWindow", "NOMINAL FORM"))
        self.label_2.setText(_translate("MainWindow", "ROLL_NUMBER"))
        self.label_3.setText(_translate("MainWindow", "USER_NAME"))

        self.comboBox.setItemText(0, _translate("MainWindow", "SELECT"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MORNING"))
        self.comboBox.setItemText(2, _translate("MainWindow", "EVENING"))

        self.label_4.setText(_translate("MainWindow", "DAYTIME"))

        self.pushButton.setText(_translate("MainWindow", "SUBMIT"))
        # ***************************main_methodra_babu******
        self.pushButton.clicked.connect(self.clicked)
        self.menuAttendance.setTitle(_translate("MainWindow", "Attendance"))

    def clicked(self, index):
        index = self.comboBox.currentIndex()
        x = datetime.datetime.now()

        if index == 1:

            my_cursor.execute("INSERT INTO nominal_mor(roll_no,user_name,today) values('%s','%s','%s')" % (
                self.lineEdit.text(), self.lineEdit_2.text(), x))

        elif index == 2:
            my_cursor.execute("INSERT INTO nominal_eve(roll_no,user_name,today) VALUES ('%s','%s','%s')" % (
                self.lineEdit.text(), self.lineEdit_2.text(), x))

        else:
            pass
        con.commit()
        QtWidgets.QMessageBox.information(
            None, 'Success', 'Attendance marked successfully.')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
